import { createFileRoute, Link } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useEffect, useRef, useState } from "react";
import { toast } from "sonner";
import {
  ArrowLeft,
  CheckCircle2,
  ClipboardCopy,
  Link2,
  ListChecks,
  Loader2,
  Printer,
  RefreshCw,
  Sparkles,
} from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { processMeeting } from "@/lib/meetings.functions";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Checkbox } from "@/components/ui/checkbox";
import { Skeleton } from "@/components/ui/skeleton";
import { cn } from "@/lib/utils";
import {
  STATUS_LABEL,
  formatDuration,
  formatTimestamp,
  type ActionItem,
  type MeetingSummary,
  type Segment,
} from "@/lib/meeting-utils";

export const Route = createFileRoute("/_authenticated/meetings/$id")({
  head: () => ({
    meta: [
      { title: "Meeting recap — Hello_Ai" },
      { name: "description", content: "Transcript, summary, decisions and action items generated by Hello_Ai." },
      { property: "og:title", content: "Meeting recap — Hello_Ai" },
      { property: "og:description", content: "AI transcript and action items for this meeting." },
    ],
  }),
  component: MeetingDetail,
});

type Meeting = {
  id: string;
  title: string;
  status: string;
  tags: string[];
  duration_seconds: number | null;
  meeting_date: string;
  transcript: string | null;
  segments: Segment[];
  summary: MeetingSummary | null;
  error_message: string | null;
  share_token: string | null;
  audio_path: string | null;
};

function buildDigest(meeting: Meeting, items: ActionItem[]) {
  const lines = [`${meeting.title}`, new Date(meeting.meeting_date).toLocaleString(), ""];
  if (meeting.summary?.overview) lines.push("Summary", meeting.summary.overview, "");
  if (meeting.summary?.key_points?.length)
    lines.push("Key points", ...meeting.summary.key_points.map((p) => `• ${p}`), "");
  if (meeting.summary?.decisions?.length)
    lines.push("Decisions", ...meeting.summary.decisions.map((d) => `• ${d}`), "");
  if (items.length)
    lines.push(
      "Action items",
      ...items.map(
        (i) => `• ${i.task}${i.owner ? ` — ${i.owner}` : ""}${i.due_date ? ` (due ${i.due_date})` : ""}`,
      ),
    );
  return lines.join("\n");
}

function MeetingDetail() {
  const { id } = Route.useParams();
  const queryClient = useQueryClient();
  const audioRef = useRef<HTMLAudioElement | null>(null);
  const [currentTime, setCurrentTime] = useState(0);
  const [audioUrl, setAudioUrl] = useState<string | null>(null);

  const { data: meeting, isLoading } = useQuery({
    queryKey: ["meeting", id],
    refetchInterval: (query) => {
      const status = (query.state.data as Meeting | undefined)?.status;
      return status && status !== "ready" && status !== "failed" ? 5000 : false;
    },
    queryFn: async () => {
      const { data, error } = await supabase.from("meetings").select("*").eq("id", id).single();
      if (error) throw error;
      return data as unknown as Meeting;
    },
  });

  const { data: items = [] } = useQuery({
    queryKey: ["action-items", id],
    enabled: meeting?.status === "ready",
    queryFn: async () => {
      const { data, error } = await supabase
        .from("action_items")
        .select("*")
        .eq("meeting_id", id)
        .order("created_at");
      if (error) throw error;
      return data as ActionItem[];
    },
  });

  useEffect(() => {
    if (!meeting?.audio_path) return;
    let cancelled = false;
    supabase.storage
      .from("recordings")
      .createSignedUrl(meeting.audio_path, 3600)
      .then(({ data }) => {
        if (!cancelled) setAudioUrl(data?.signedUrl ?? null);
      });
    return () => {
      cancelled = true;
    };
  }, [meeting?.audio_path]);

  const toggleItem = useMutation({
    mutationFn: async (item: ActionItem) => {
      const { error } = await supabase
        .from("action_items")
        .update({ done: !item.done })
        .eq("id", item.id);
      if (error) throw error;
    },
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ["action-items", id] }),
  });

  const share = useMutation({
    mutationFn: async () => {
      if (!meeting) return null;
      const token = meeting.share_token ?? crypto.randomUUID().replace(/-/g, "");
      if (!meeting.share_token) {
        const { error } = await supabase
          .from("meetings")
          .update({ share_token: token })
          .eq("id", meeting.id);
        if (error) throw error;
      }
      return token;
    },
    onSuccess: async (token) => {
      if (!token) return;
      await navigator.clipboard.writeText(`${window.location.origin}/share/${token}`);
      queryClient.invalidateQueries({ queryKey: ["meeting", id] });
      toast.success("Share link copied to clipboard");
    },
    onError: () => toast.error("Could not create the share link"),
  });

  const reprocess = useMutation({
    mutationFn: async () => processMeeting({ data: { meetingId: id } }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["meeting", id] });
      toast.success("Reprocessing started");
    },
    onError: () => toast.error("Could not reprocess this meeting"),
  });

  if (isLoading || !meeting) {
    return (
      <div className="space-y-4">
        <Skeleton className="h-10 w-64" />
        <Skeleton className="h-40 w-full rounded-xl" />
        <Skeleton className="h-64 w-full rounded-xl" />
      </div>
    );
  }

  const processing = meeting.status !== "ready" && meeting.status !== "failed";

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div className="min-w-0">
          <Link
            to="/dashboard"
            className="inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground"
          >
            <ArrowLeft className="size-3.5" /> All meetings
          </Link>
          <h1 className="mt-2 text-2xl font-semibold sm:text-3xl">{meeting.title}</h1>
          <div className="mt-2 flex flex-wrap items-center gap-3 text-xs text-muted-foreground">
            <span>{new Date(meeting.meeting_date).toLocaleString()}</span>
            <span>{formatDuration(meeting.duration_seconds)}</span>
            {meeting.tags.map((tag) => (
              <Badge key={tag} variant="secondary" className="rounded-full text-[11px]">
                {tag}
              </Badge>
            ))}
          </div>
        </div>
        <div className="flex flex-wrap gap-2">
          <Button
            variant="outline"
            size="sm"
            onClick={() => {
              navigator.clipboard.writeText(buildDigest(meeting, items));
              toast.success("Recap copied — paste it into Slack or email");
            }}
          >
            <ClipboardCopy className="size-4" /> Copy recap
          </Button>
          <Button variant="outline" size="sm" onClick={() => window.print()}>
            <Printer className="size-4" /> Export PDF
          </Button>
          <Button size="sm" onClick={() => share.mutate()} disabled={share.isPending}>
            <Link2 className="size-4" /> {meeting.share_token ? "Copy share link" : "Share"}
          </Button>
        </div>
      </div>

      {processing && (
        <div className="surface-panel flex items-center gap-3 p-5">
          <Loader2 className="size-5 animate-spin text-primary" />
          <div>
            <p className="text-sm font-medium">{STATUS_LABEL[meeting.status] ?? meeting.status}…</p>
            <p className="text-xs text-muted-foreground">
              Hello_Ai is working through the audio. This page updates itself.
            </p>
          </div>
        </div>
      )}

      {meeting.status === "failed" && (
        <div className="surface-panel flex flex-wrap items-center justify-between gap-3 border-destructive/40 p-5">
          <div>
            <p className="text-sm font-medium text-destructive">Processing failed</p>
            <p className="text-xs text-muted-foreground">
              {meeting.error_message ?? "Something went wrong while transcribing."}
            </p>
          </div>
          <Button size="sm" variant="outline" onClick={() => reprocess.mutate()} disabled={reprocess.isPending}>
            <RefreshCw className={cn("size-4", reprocess.isPending && "animate-spin")} /> Try again
          </Button>
        </div>
      )}

      {audioUrl && (
        <div className="surface-panel p-4">
          <audio
            ref={audioRef}
            src={audioUrl}
            controls
            className="w-full"
            onTimeUpdate={(e) => setCurrentTime(e.currentTarget.currentTime)}
          />
        </div>
      )}

      {meeting.summary && (
        <div className="grid gap-4 lg:grid-cols-3">
          <div className="surface-panel p-5 lg:col-span-2">
            <h2 className="flex items-center gap-2 text-sm font-semibold text-primary">
              <Sparkles className="size-4" /> Summary
            </h2>
            <p className="mt-3 text-sm leading-relaxed text-foreground/90">{meeting.summary.overview}</p>
            {meeting.summary.topics?.length > 0 && (
              <div className="mt-4 flex flex-wrap gap-2">
                {meeting.summary.topics.map((topic) => (
                  <Badge key={topic} variant="outline" className="rounded-full text-[11px]">
                    {topic}
                  </Badge>
                ))}
              </div>
            )}
          </div>

          <div className="surface-panel p-5">
            <h2 className="flex items-center gap-2 text-sm font-semibold">
              <ListChecks className="size-4 text-primary" /> Action items
            </h2>
            {items.length === 0 ? (
              <p className="mt-3 text-sm text-muted-foreground">No action items detected.</p>
            ) : (
              <ul className="mt-3 space-y-3">
                {items.map((item) => (
                  <li key={item.id} className="flex items-start gap-2.5">
                    <Checkbox
                      checked={item.done}
                      onCheckedChange={() => toggleItem.mutate(item)}
                      className="mt-0.5"
                    />
                    <div className="min-w-0 text-sm">
                      <p className={cn(item.done && "text-muted-foreground line-through")}>{item.task}</p>
                      {(item.owner || item.due_date) && (
                        <p className="mt-0.5 text-xs text-muted-foreground">
                          {item.owner ?? "Unassigned"}
                          {item.due_date ? ` · due ${item.due_date}` : ""}
                        </p>
                      )}
                    </div>
                  </li>
                ))}
              </ul>
            )}
          </div>

          <div className="surface-panel p-5">
            <h2 className="text-sm font-semibold">Key points</h2>
            <ul className="mt-3 space-y-2 text-sm text-foreground/90">
              {(meeting.summary.key_points ?? []).map((point, i) => (
                <li key={i} className="flex gap-2">
                  <span className="mt-1.5 size-1.5 shrink-0 rounded-full bg-primary" />
                  {point}
                </li>
              ))}
            </ul>
          </div>

          <div className="surface-panel p-5 lg:col-span-2">
            <h2 className="text-sm font-semibold">Decisions</h2>
            {meeting.summary.decisions?.length ? (
              <ul className="mt-3 space-y-2 text-sm text-foreground/90">
                {meeting.summary.decisions.map((decision, i) => (
                  <li key={i} className="flex gap-2">
                    <CheckCircle2 className="mt-0.5 size-4 shrink-0 text-success" />
                    {decision}
                  </li>
                ))}
              </ul>
            ) : (
              <p className="mt-3 text-sm text-muted-foreground">No explicit decisions were made.</p>
            )}
          </div>
        </div>
      )}

      {meeting.segments?.length > 0 && (
        <div className="surface-panel p-5">
          <h2 className="text-sm font-semibold">Transcript</h2>
          <div className="mt-4 max-h-[32rem] space-y-1 overflow-y-auto pr-1">
            {meeting.segments.map((segment, i) => {
              const active =
                currentTime >= segment.start && (segment.end == null || currentTime < segment.end);
              return (
                <button
                  key={i}
                  onClick={() => {
                    if (audioRef.current) {
                      audioRef.current.currentTime = segment.start;
                      void audioRef.current.play();
                    }
                  }}
                  className={cn(
                    "flex w-full gap-3 rounded-lg px-3 py-2 text-left transition-colors hover:bg-surface",
                    active && "bg-accent",
                  )}
                >
                  <span className="font-mono text-xs text-muted-foreground">
                    {formatTimestamp(segment.start)}
                  </span>
                  <span className="min-w-0 text-sm">
                    <span className="font-medium text-primary">{segment.speaker}: </span>
                    {segment.text}
                  </span>
                </button>
              );
            })}
          </div>
        </div>
      )}
    </div>
  );
}
